title: Pointless musings
email: $"RFC3696"IS\\Best RFC=hurray@growse.com
description: > # this means to ignore newlines until "baseurl:"
  DESCRIPTIONG
baseurl: ""
url: "https://www.growse.com"

assets:
  prefix: "/static"
  assets:
   - "*.css"
   - "*.scss"
   - "*.woff"
   - "*.js"
   - "*.png"
  sources:
   - _assets/css
   - _assets/js
   - _assets/fonts
   - _assets/img


markdown: kramdown
gems:
  - jekyll-feed
  - jekyll-assets
  - jekyll-sitemap
exclude:
  - Gemfile
  - Gemfile.lock
  - "*.iml"
