title: Pointless musings
email: $"RFC3696"IS\\Best RFC=hurray@growse.com
description: > # this means to ignore newlines until "baseurl:"
  DESCRIPTIONG
baseurl: ""
url: "https://www.growse.com"

monthly_archive:
  path: "/archive"

markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-assets
  - jekyll-sitemap
exclude:
  - Gemfile
  - Gemfile.lock
  - "*.iml"
  - vendor
